# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RN_59' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  node_modules_path = '../node_modules'
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # Pods for RN_59
  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]

  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # CodePush plugin dependency

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'Firebase'

  pod 'Firebase/Messaging'

  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end